version: "2.2"    

services:
  larpmdbmysql:
    image: mariadb:10.5.12
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: larpm
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    
  larpm:
    build: .
    depends_on:
      - larpmdbmysql
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./src:/usr/src/larpmanager/src
      - ./web:/usr/src/larpmanager/web
      - ./app:/usr/src/larpmanager/app

